services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    container_name: lms_app
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - COMPOSER_HOME=/tmp/composer
    volumes:
      - ./website:/opt/drupal
    working_dir: /opt/drupal
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lms_network

  web:
    image: nginx:1.29
    container_name: lms_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./website:/opt/drupal
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lms_network

  db:
    image: mariadb:10.11
    container_name: lms_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lms_db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lms_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: lms_mailpit
    restart: always
    ports:
      - "8025:8025" # Interfaz Web (Dashboard)
      - "1025:1025" # Puerto SMTP
    networks:
      - lms_network

volumes:
  db_data:

networks:
  lms_network:
    driver: bridge